### ISSUE TITLE
Authentication mechanism

### ISSUE THREAD

**Issue by ivanfoong** [jobsgowhere/jobsgowhere#11]
There's a few authentication mechanisms that I can think of to support:
1. Our own signup/login
1. LinkedIn <https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin?context=linkedin/consumer/context>
1. Google Sign-in <https://developers.google.com/identity/sign-in/web/sign-in>

### Pros
1. ability to load work profile for job seekers
1. ability to load company profile for job posters
### Cons
1. user base needs to have LinkedIn account

### Pros
1. more likely to have a gmail account for most user base
### Cons
1. not much information to pre-populate other than email address

Would we want to only help users with LinkedIn account? Older non tech savvy folks might not have LinkedIn account, but then again they might not even use our app.

**Comment by subhransu** [comment]
My initial thought was if we want to share about a job post on LinkedIn it's going to be easier if we already have LinkedIn authentication in place otherwise we can always add it later.

**Comment by ivanfoong** [comment]
I think we should go with LinkedIn anyway, as the more I think about it, I think the user population are likely to have LinkedIn account. And prepopulating the job search profile might be very useful in helping new sign ups

**Comment by subhransu** [comment]
I am closing this issue as we decided to go with LinkedIn for first version. We can revisit this later after the first version is released.
