### ISSUE TITLE
Backend - Editing Profile causes profile_type field to cleared

### ISSUE THREAD

**Issue by SheldonCheng** [jobsgowhere/jobsgowhere#123]
Sign in with LinkedIn and fill up your profile (happy path). If you edit your profile afterwards (PUT request to /api/profile),  the `profile_type` field becomes `""`

Screenshot of response GET /api/profile after doing an edit:
![image](https://user-images.githubusercontent.com/3888250/91475036-95f4a780-e8cd-11ea-85a3-84026bdbffcc.png)

This seems to happen no matter what field I edit.

### Sidenote:
@subhransu I noticed on initial Profile creation, that filling either one of **Headline** or **Website** fields and leaving the other blank, will result in the profile `status` as `"Complete"`. Is this correct?

**Comment by subhransu** [comment]
@SheldonCheng are you passing the `profile_type` field while editing? You still need to send all the fields.

**Comment by SheldonCheng** [comment]
@subhransu ohh yeah the Edit call is not sending `profile_type` , so the backend reads and sets as empty?

Didn’t occur to me because the profile type selector is not used in Edit mode

**Comment by SheldonCheng** [comment]
So I didn't fully understand what the endpoint was expecting. I have updated the Edit form to prevent this issue, hence closing it.

**Comment by SheldonCheng** [comment]
Ok I think I understand this now. I have updated Edit form submission to also submit `profile_type` so backend does not erase the value.
PR #125 is still needed because if user did not choose "Recruiter" on profile creation, then subsequent Edits to change to "Recruiter" will have error. Will let #125 close this issue once that is ready.
