### ISSUE TITLE
Backend - POST Job responds with 500 internal server error

### ISSUE THREAD

**Issue by SheldonCheng** [jobsgowhere/jobsgowhere#124]
Calling **POST Job** (/api/job) with valid request causes server to return `500 Internal Server Error` with no body.
The **job** table still **does get populated** in database.
This happens even in Postman, so please try it there.

**POST Talent** api works fine so far 🙌.

### Somewhat related:
It seems POST Job api is missing a field for job link.
I think this got overlooked because previously the backend was expecting the `website_url` to come from Profile creation flow.

![image](https://user-images.githubusercontent.com/3888250/91480534-b0cb1a00-e8d5-11ea-8cd6-64f4dbe1a1c7.png)

**Comment by subhransu** [comment]
This is what we talked about in the sync-up call. @hanmd82 will add the `job_link_url` field. 
But the postman should be working. 

@SheldonCheng Did you try creating the job after editing the profile? In other words, do you have a JobProvider created in the DB for the `iam_id`? It should have been automatically created the first time. If not one of the flow is missing?

**Comment by SheldonCheng** [comment]
@subhransu ah you're right, I forgot this branch does not have the profile creation implemented, my bad 😓
It works when the job_provider table has the proper entry.

Noted on the `job_link_url` field. So this is a non-issue, will close this. 🙏
