### ISSUE TITLE
Infinite sign-in issue.

### ISSUE THREAD

**Issue by zr-faisal** [jobsgowhere/jobsgowhere#127]
Steps:

1. Navigate to jobsgowhere from a local build
2. Signin with LinkedIn
3. The SignIn button appears again and falls into a loop [(see attached video)!](https://github.com/jobsgowhere/jobsgowhere/files/5157490/JobsGoWhere.Infinite.Signin.mov.zip)

**Comment by subhransu** [comment]
@zr-faisal can you post the redirect URLs from your .env files under `.env.development` ... also did you try running the go server or just running the react build?

**Comment by subhransu** [comment]
Closed. There were missing credentials in the local `env`
