### ISSUE TITLE
Backend - LinkedIn Login Integration

### ISSUE THREAD

**Issue by subhransu** [jobsgowhere/jobsgowhere#20]

**Comment by ivanfoong** [comment]
Will reference an example at https://github.com/denisbakhtin/oauth2-example/blob/master/linkedin/linkedin.go

**Comment by ivanfoong** [comment]
Seems like we might not be able to get user's full profile. As stated in <https://docs.microsoft.com/en-us/linkedin/shared/references/v2/profile/lite-profile> `r_liteprofile` permission only allow access to these 4 fields:
1. `id`
2. `firstName`
3. `lastName`
4. `profilePicture`

The change happened after they moved to v2 API <https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/migration-faq?context=linkedin/consumer/context>. Not a blocker for what we need now, but kind of defeats the reason of choosing LinkedIn over other OAuth providers. FYI We are still able to get user's email

**Comment by ivanfoong** [comment]
Partial complete in #56, able to oauth redirect and retrieve first/last name, email. Just missing database persistence.

@kajalsinha will help to create the right code structure and implement data persistence

**Comment by kajalsinha** [comment]
@ivanfoong @subhransu , I will start working on this one now.

**Comment by subhransu** [comment]
marking this as closed as LinkedIn Login flow is working. I will create separate issues for profile/onboarding API.
