### ISSUE TITLE
Bug - Content overflows in Mobile view

### ISSUE THREAD

**Issue by jacobtyq** [jobsgowhere/jobsgowhere#200]
Description
---
- [ ] Content to occupy full width in mobile view
- [ ] Change character limit to 1000

Screenshot
---
![Screenshot_20201124-131859](https://user-images.githubusercontent.com/6391234/100179114-434c7b00-2f10-11eb-99bd-10b1b2b71b50.png)

**Comment by SheldonCheng** [comment]
@jacobtyq Can elaborate on what scenario the ellipsis will appear?

**Comment by jacobtyq** [comment]
@SheldonCheng probably when text cuts off like in this screenshot. But rethinking this now maybe it is not required as it is not a excerpt. 

What do you think?

**Comment by SheldonCheng** [comment]
It shows the full content of the user's text, so I cannot see why an ellipsis is needed.

My guess for what happened above is that Andana just pasted a chunk of text and hit submit, without realising that it crossed the char limit and got truncated.
