### ISSUE TITLE
DetailsContainer not scrollable

### ISSUE THREAD

**Issue by cheeaun** [jobsgowhere/jobsgowhere#217]
Page with `<DetailsContainer />` doesn't seem scrollable on small-screen devices.

Here's an inspect:
<img width="1552" alt="Screenshot 2020-12-17 at 11 30 28 AM" src="https://user-images.githubusercontent.com/2296/102440566-6ffd3980-405b-11eb-992d-c3cab3a96cb4.png">

There's `position: absolute`, but disabling it enables `position: sticky`. Disabling both `position` also don't make it scrollable, maybe... due to the grid. Seems kinda hacky at this point but solution seems like put `bottom: 0; overflow: auto` to it, but there's another hidden footer taking up space at the bottom 😅 

Up to you guys to solve this 😛

**Comment by SheldonCheng** [comment]
Eeks, I knew I didn't test this properly. Thanks for reporting this 😅🙏
