### ISSUE TITLE
Frontend - Fetch jobs from API and display

### ISSUE THREAD

**Issue by SheldonCheng** [jobsgowhere/jobsgowhere#34]

**Comment by subhransu** [comment]
Mock API path: http://dev.jobsgowhere.com/api/jobs
You need to pass the basic auth credentials in the header I guess.

**Comment by subhransu** [comment]
blocked by backend API at the moment.

**Comment by subhransu** [comment]
## API spec until we have a proper Postman or Swagger documentation

* GET All Jobs `api/jobs/<page_number>` example [http://dev.jobsgowhere.com/api/jobs/1](http://dev.jobsgowhere.com/api/jobs/1)

* Get Job Description `api/jobsbyid/<job_id>` example [http://dev.jobsgowhere.com/api/jobsbyid/f5bebcb8-6ba8-4ae5-a734-a1187e31b2ab](http://dev.jobsgowhere.com/api/jobsbyid/f5bebcb8-6ba8-4ae5-a734-a1187e31b2ab)

**Comment by subhransu** [comment]
Closing this as this is done.
