### ISSUE TITLE
Frontend - Fetch talents from API and display

### ISSUE THREAD

**Issue by SheldonCheng** [jobsgowhere/jobsgowhere#35]

**Comment by subhransu** [comment]
blocked by backend API at the moment.

**Comment by subhransu** [comment]
##Talents API

GET All Talents `api/jobs/<page_number>` example [http://dev.jobsgowhere.com/api/talents/1](http://dev.jobsgowhere.com/api/talents/1)

Get Talent by ID `api/talentsbyid/<talent_id>` example [http://dev.jobsgowhere.com/api/talentsbyid/ede93b1b-d84d-4944-b46d-bb3c9d26ddc9](http://dev.jobsgowhere.com/api/talentsbyid/ede93b1b-d84d-4944-b46d-bb3c9d26ddc9)

**Comment by subhransu** [comment]
Closing this as this is done.
