### ISSUE TITLE
Figure out the frontend architecture

### ISSUE THREAD

**Issue by lxcid** [jobsgowhere/jobsgowhere#4]
> From #1 

Should be assigned to @lxcid and @SheldonCheng

## Action Items

- Find out whether you want to use React / Next.js or both with golang backend (@lxcid and @SheldonCheng to discuss)
  - @SheldonCheng: for integration with golang, it shoudln't be too different from react i think.
    it can be built into static html and served, just that initial api calls and page rendering happens on server
    don't think we will have a lot of static pages so perhaps no great advantage to using nextjs here (other than SEO maybe). So prob can just use standard react
- TypeScript or JavaScript
  - TypeScript, learning experience for implementors

**Comment by subhransu** [comment]
@lxcid I think this is done? 
As in finalizing what frameworks you need to use? If yes feel free to close this issue.

**Comment by lxcid** [comment]
Yeah this is done.
