### ISSUE TITLE
Bug - Change frontend API URL

### ISSUE THREAD

**Issue by subhransu** [jobsgowhere/jobsgowhere#42]
Deployed the latest code to dev.jobsgowhere.com 

However, it fails to fetch the response as the URL is hardcoded to the localhost.
<img width="966" alt="Screenshot 2020-04-10 at 11 08 45 PM" src="https://user-images.githubusercontent.com/1495621/79001059-63494d00-7b80-11ea-93b0-41f5a42c167e.png">

Replace this to point the hardcoded URL to HOST_URL

**Comment by SheldonCheng** [comment]
Oops, https://github.com/jobsgowhere/jobsgowhere/pull/43 will fix this.

**Comment by SheldonCheng** [comment]
Fixed in https://github.com/jobsgowhere/jobsgowhere/pull/44.
