### ISSUE TITLE
Create basic database structure of jobsgowhere

### ISSUE THREAD

**Issue by kajalsinha** [jobsgowhere/jobsgowhere#51]
I was thinking of creating a basic table structure which should be strong enough to get started. This is just the beginning so foreign key references are not mapped. I want to design it in a way that in future it can be broken down to micro services by feature i.e.  set of related features can be grouped in one micro service.

Please suggest changes/thoughts. Thanks!

```SQL
-- Add your release scripts here
CREATE TABLE person
(
    id           UUID PRIMARY KEY,
    iam_id       TEXT      NOT NULL UNIQUE,
    dp_url       TEXT,
    email        TEXT      NOT NULL,
    iam_provider TEXT      NOT NULL,
    created_at   TIMESTAMP NOT NULL,
    CONSTRAINT UNIQUE (email, iam_provider)
);

CREATE TABLE job
(
    id          UUID PRIMARY KEY,
    title       TEXT      NOT NULL,
    description TEXT      NOT NULL,
    location    TEXT      NOT NULL,
    created_by  TEXT      NOT NULL,
    created_at  TIMESTAMP NOT NULL
);

CREATE TABLE skill
(
    id          UUID PRIMARY KEY,
    title       TEXT UNIQUE NOT NULL,
    description TEXT
);


CREATE TABLE related_skills (
    -- todo
)

CREATE TABLE job_skill_map
(
    job_id   UUID NOT NULL,
    skill_id UUID NOT NULL,
    required BOOL DEFAULT FALSE,
);

CREATE TABLE job_seeker
(
    person_id       UUID PRIMARY KEY,
    title           TEXT      NOT NULL,
    current_company TEXT,
    created_at      TIMESTAMP NOT NULL
);

CREATE TABLE job_provider
(
    person_id       UUID PRIMARY KEY,
    title           TEXT      NOT NULL,
    current_company TEXT      NOT NULL,
    created_at      TIMESTAMP NOT NULL
);
```

**Comment by ivanfoong** [comment]
There's some fields that's different from what we have at https://github.com/jobsgowhere/jobsgowhere/tree/master/data, like missing first and last name. And is skillset a new field for users?

**Comment by kajalsinha** [comment]
we will need to mapping of skillset so I was putting in model. The apis will be there in future. Adding a few features at the table level helps to create more scalable design.
I will add `first name` and `last name`

**Comment by subhransu** [comment]
`skill` will have probably one more URL for resume and LinkedIn profile URL? 

`job` probably needs a column for keywords or tags?

**Comment by subhransu** [comment]
@ivanfoong take a look at this: https://www.youtube.com/watch?v=fKmRemtmi0Y

This is a good start to understand SQLBolier. Similar concepts like ActiveRecord in Rails.

**Comment by subhransu** [comment]
Closing as this is done.
